name: INDEX_GXA_CI
on: pull_request

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Make exps designs writable
        run: |
          chmod a+w tests/fixtures/experiment_files/expdesign/*
          chmod a+w tests/fixtures/experiment_files/expdesign
      - name: Run tests from containers
        run: bash run_tests_in_containers.sh
